name: Lighthouse CI

on:
  pull_request:

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for Vercel Preview
        id: vercel_preview
        uses: ancor-travel/wait-for-vercel-preview@v1
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.head_ref }}
          token: ${{ secrets.VERCEL_TOKEN }}
          max_timeout: 600

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lighthouse CI
        run: |
          pnpm add -D @lhci/cli
          lhci autorun --collect.url=${{ steps.vercel_preview.outputs.url }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }} 