name: Nightly Content Generation

on:
  schedule:
    # Corre às 03:00 UTC todos os dias
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  generate_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate MDX files
        run: pnpm generate-mdx

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: auto-generate MDX files"
            git push
          else
            echo "No changes to commit."
          fi 